version: '3.8'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,lambda,dynamodb,cognito,apigateway,iam,sts,cloudwatch
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - e-commerce-net

  product-catalog:
    image: ja5on96/product-catalog:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8089:8089"
    deploy:
      replicas: 1
    networks:
      - e-commerce-net

  order:
    image: ja5on96/order-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8090"
    deploy:
      replicas: 1
    networks:
      - e-commerce-net

volumes:
  localstack_data:
    driver: local

networks:
  e-commerce-net:
