version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs,lambda,dynamodb,cognito,apigateway,iam,sts,cloudwatch
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - ./localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  product-catalog:
    build: ./product-catalog
    depends_on:
      - localstack
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8089:8089"

  order:
    build: ./order
    depends_on:
      - localstack
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8090:8090"
      
volumes:
  localstack_data:
    driver: local
