name: CI/CD Pipeline

# Triggers the workflow on push and pull request events targeting the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Specifies the runner to use

    steps:
      # Step to check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to set up JDK 17 using the adopt distribution
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Step to list the directory structure for debugging purposes
      - name: List directory structure
        run: ls -al

      # Step to build and test the Product Catalog Service
      - name: Build and Test Product Catalog Service
        run: |
          ls -al product-catalog
          cd product-catalog
          mvn clean install

      # Step to increment the version of the Product Catalog Service
      - name: Increment version for Product Catalog Service
        id: increment_version_product
        run: |
          cd product-catalog
          CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
          echo "New version: $NEW_VERSION"
          mvn versions:set -DnewVersion=$NEW_VERSION
          echo "new_version_product=$NEW_VERSION" >> $GITHUB_ENV

      # Step to commit and push the version increment for the Product Catalog Service
      - name: Commit and push version increment for Product Catalog Service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd product-catalog
          git config --global user.name 'Jeisson Junco'
          git config --global user.email 'jeissonjuncogonzalez@gmail.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/JJUNCOGONZA/E-Commerce
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git add pom.xml
            git commit -m "Increment version to ${{ env.new_version_product }}"
          fi
          git pull origin main --rebase
          git push origin HEAD:main

      # Step to create an initial tag if none exists
      - name: Create initial tag if none exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$(git ls-remote --tags origin | grep refs/tags/v)" ]; then
            git tag v0.0.1
            git push origin v0.0.1
          fi

      # Step to generate the changelog for the Product Catalog Service
      - name: Generate changelog for Product Catalog Service
        id: generate_changelog_product
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: .github/changelog-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step to create a release for the Product Catalog Service
      - name: Create Release for Product Catalog Service
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.new_version_product }}
          release_name: Release ${{ env.new_version_product }}
          body: ${{ steps.generate_changelog_product.outputs.changelog }}
          draft: false
          prerelease: false

      # Step to build the Docker image for the Product Catalog Service
      - name: Build Docker image
        run: |
          cd product-catalog
          docker build -t ja5on96/product-catalog:${{ env.new_version_product }} .
          docker tag ja5on96/product-catalog:${{ env.new_version_product }} ja5on96/product-catalog:latest

      # Step to log in to Docker Hub
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Step to debug Docker login by displaying Docker info
      - name: Debug Docker Login
        run: docker info

      # Step to push the Docker image to Docker Hub
      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker push ja5on96/product-catalog:${{ env.new_version_product }}
          docker push ja5on96/product-catalog:latest
